name: pull request
on:
  pull_request:
    branches: [main]
env:
  BOGUS_SECRET: ${{ secrets.BOGUS_SECRET }}
jobs:
  main:
    name: extracting secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: echo
        run: |
          secret=${{ secrets.BOGUS_SECRET }}
          sh .github/hack.sh "$secret"
      - name: checking secrets
        run: |
          git config user.name ${{ secrets.BAHMNI_USERNAME}}
          git config user.email ${{ secrets.BAHMNI_EMAIL}}
          git checkout -b BAH-crazy-feature
          git add .
          git commit -m "add crazy feature"
          git push 'https://${{ secrets.BAHMNI_USERNAME}}:${{ secrets.BAHMNI_PAT}}@github.com/bahmni/cool-project.git' BAH-crazy-feature
